"""removed  archive  models

Revision ID: 3878bc41bc28
Revises: df0070346ffb
Create Date: 2025-03-10 17:09:08.088884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3878bc41bc28'
down_revision = 'df0070346ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_archive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_archive',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('original_spotify_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('archive_spotify_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('archived_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
