"""new

Revision ID: 447c7d2d7e1e
Revises: 53f07c77ebc5
Create Date: 2025-03-20 19:05:27.223004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447c7d2d7e1e'
down_revision = '53f07c77ebc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_comment', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
