"""Describe your migration

Revision ID: 53f07c77ebc5
Revises: 3878bc41bc28
Create Date: 2025-03-20 19:03:20.959030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f07c77ebc5'
down_revision = '3878bc41bc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_comment', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(length=500), nullable=False))

    # ### end Alembic commands ###
