"""empty message

Revision ID: 86a19b058a99
Revises: 410d9f11a492
Create Date: 2025-03-08 22:41:33.682379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a19b058a99'
down_revision = '410d9f11a492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_track_per_playlist', ['playlist_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_constraint('unique_track_per_playlist', type_='unique')

    # ### end Alembic commands ###
