"""empty message

Revision ID: 8edab4b5fa9e
Revises: 642e5fd2b011
Create Date: 2025-03-09 16:56:31.542427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edab4b5fa9e'
down_revision = '642e5fd2b011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_playlist_per_user', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_constraint('unique_playlist_per_user', type_='unique')

    # ### end Alembic commands ###
