"""removed  workout transition models

Revision ID: df0070346ffb
Revises: 52f3eb00063a
Create Date: 2025-03-10 15:41:53.368560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0070346ffb'
down_revision = '52f3eb00063a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_transition')
    op.drop_table('workout_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('workout_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('target_bpm', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_transition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), nullable=False),
    sa.Column('from_track', sa.VARCHAR(length=100), nullable=False),
    sa.Column('to_track', sa.VARCHAR(length=100), nullable=False),
    sa.Column('transition_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
