"""Enforce non-null spotify_track_id

Revision ID: fffcb271b3db
Revises: 96f4002e643a
Create Date: 2025-03-09 00:02:13.465199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffcb271b3db'
down_revision = '96f4002e643a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_track')
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.alter_column('spotify_track_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.alter_column('spotify_track_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    op.create_table('_alembic_tmp_track',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('artist', sa.VARCHAR(length=200), nullable=False),
    sa.Column('album', sa.VARCHAR(length=200), nullable=True),
    sa.Column('playlist_id', sa.INTEGER(), nullable=False),
    sa.Column('spotify_track_id', sa.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name='fk_track_playlist', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'name', name='unique_track_per_playlist')
    )
    # ### end Alembic commands ###
